### ISSUE TITLE
Website isn't working?

### ISSUE THREAD

**Issue by erezsh** [christianmemije/sortify#2]
I logged in with my spotify account and it doesn't show anything. The upper right button isn't working either.

**Comment by christianmemije** [comment]
@erezsh Thanks for your interest in wanting to try out the app! What browser and version are you using? Any screenshots or console errors?

**Comment by erezsh** [comment]
Chrome Version 79.0.3945.130 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/731464/73305231-5b853800-4222-11ea-892f-ebc1b6514fe5.png)

**Comment by christianmemije** [comment]
Hard to tell what exactly is undefined. Can you expand the stack trace? I also just pushed a commit to avoid accessing unsafe url properties. Can you check sortify-app.now.sh whether the issue persists?

**Comment by erezsh** [comment]
Okay, it's working now. You can close this issuse.

Btw, any chance you can display the averages+range for each list? That way I can choose lists based on what's the loudest song, average tempo, etc.

**Comment by christianmemije** [comment]
Nice. Let's close this issue and feel free to open an issue requesting that feature. At the top of my head, I could see it being computationally heavy.
