### ISSUE TITLE
Podcasts are disappearing

### ISSUE THREAD

**Issue by christianmemije** [christianmemije/sortify#37]
> I happened to have my Spotify podcasts disappearing after saving my sorted playlist. The tracks are still on the site while and after sorting but they're not on the Spotify app anymore. Refreshed the site too and the podcasts just completely disappeared. Hope you can find a way on how to fix this.. If not i'll probably just resort to making a separate playlist for the podcasts lol(the podcasts involves songs that aren't on spotify btw !)

**Comment by AlexRyuCoding** [comment]
closed in https://github.com/christianmemije/sortify/pull/50
