### ISSUE TITLE
Smarter sorting options

### ISSUE THREAD

**Issue by sbeyer** [christianmemije/sortify#41]
I used the tool to sort by artist, but now artists beginning with a small letter are at the bottom.

Would be cool to have an option to sort case-insensitive.

Moreover, bands starting with Æ or É are at the bottom, but it would be nice to have such letters be interpreted (for sorting) as A and E respectively.

**Comment by christianmemije** [comment]
To handle character variations we need to do something like

```
.normalize("NFD").replace(/[\u0300-\u036f]/g, "");
```

**Comment by christianmemije** [comment]
Will stick to just normalizing case to not go down the rabbit hole of normalizing different characters.

**Comment by sbeyer** [comment]
Fair enough, thank you!
